[variables]
email = "jane@personal.com"
editor = "code"

[[dotfiles]]
source = "dotfiles/zsh/zshrc"
target = "~/.zshrc"

[[dotfiles]]
source = "dotfiles/git/gitconfig"
target = "~/.gitconfig"

[[dotfiles]]
source = "dotfiles/vim/vimrc"
target = "~/.vimrc"

[[dotfiles]]
source = "dotfiles/tmux/tmux.conf"
target = "~/.tmux.conf"

[[packages.homebrew]]
name = "git"
type = "formula"

[[packages.homebrew]]
name = "neovim"
type = "formula"

[[packages.homebrew]]
name = "tmux"
type = "formula"

[[packages.homebrew]]
name = "fzf"
type = "formula"

[[packages.homebrew]]
name = "visual-studio-code"
type = "cask"
