[variables]
email = "jane@personal.com"
editor = "code"

[[dotfiles]]
source = "dotfiles/zsh/zshrc"
target = "~/.zshrc"

[[dotfiles]]
source = "dotfiles/git/gitconfig"
target = "~/.gitconfig"

[[dotfiles]]
source = "dotfiles/vim/vimrc"
target = "~/.vimrc"

[[dotfiles]]
source = "dotfiles/tmux/tmux.conf"
target = "~/.tmux.conf"

[packages]
brew = ["git", "neovim", "tmux", "fzf"]
cask = ["visual-studio-code"]
