[variables]
email = "jane.smith@work.com"
editor = "vim"

[[dotfiles]]
source = "dotfiles/zsh/zshrc"
target = "~/.zshrc"

[[dotfiles]]
source = "dotfiles/git/gitconfig"
target = "~/.gitconfig"

[packages]
brew = ["git", "tmux"]
cask = ["docker"]
